version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - .env
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/./app/
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgres_volume:
