version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=my_dj_ps_dock
    ports:
      - 5432:5432
  web:
    build: .
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    healthcheck:
      interval: 20s
    volumes:
      - .:/./app/
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgres_volume: